mod 'puppet/nginx', '4.0.0'
mod 'puppetlabs-java', '9.0.0'
mod 'puppetlabs-tomcat', '6.3.0'
mod 'puppet-archive', '6.0.2'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
